network:
  name: sample_network
  description: Vapor Line
  direction: forward
  gas_flow_model: adiabatic
  boundary_pressure:
    value: 101.08
    unit: kPag
  temperature:
    value: 35.0
    unit: degC
  mass_flow_rate:
    value: 1000.0
    unit: kg/h
  output_units:
    pressure: kPag
    pressure_drop: kPa
    temperature: degC
    density: kg/m^3
    velocity: m/s
    volumetric_flow_rate: m^3/h
    mass_flow_rate: kg/h
    flow_momentum: Pa
    gas_flow_critical_pressure: kPa
    length: m
    small_length: mm
  fluid:
    name: gas
    phase: gas
    molecular_weight: 28.0 # Example value for gas
    z_factor: 0.9 # Example value for gas
    specific_heat_ratio: 1.3 # Example value for gas
    viscosity:
      value: 0.012
      unit: cP # Example value for gas
  sections:
    - id: "1"
      schedule: "40"
      pipe_NPD: 4.0
      roughness: 4.57e-5
      length:
        value: 1000.0
        unit: m
      erosional_constant: 100
      fitting_type: LR
      piping_and_fitting_safety_factor: null